version: "3"
services:
    timescaledb:
        image: timescale/timescaledb:latest-pg11
        command: postgres -c 'max_connections=200'
        environment:
            POSTGRES_PASSWORD: "password"
        ports:
            - "5432:5432"
    backend:
        image: cicd
        ports:
            - "80:80"
            - "443:443"